apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ek8sms-base

resources:
  - rbac.yaml
  - mcpserver-ek8sms.yaml

commonLabels:
  app.kubernetes.io/name: ek8sms
  app.kubernetes.io/component: mcp-server
  app.kubernetes.io/part-of: kubernetes-mcp
  app.kubernetes.io/managed-by: kustomize

namespace: default
